blank_issues_enabled: false
contact_links:
  - name: Ideas and Feature Requests ğŸš€
    url: https://github.com/{REPLACE_WITH_REPO_NAME}/discussions/categories/ideas
    about: If you have an idea or would like to make a feature request please open a discussion thread.

  - name: Support and Questions â“
    url: https://github.com/{REPLACE_WITH_REPO_NAME}/discussions/categories/q-a
    about: Need help or just have a general question? Please open a discussion thread.
